
services:
   
    restful-flask-apl-hello-universe:

        container_name: restful-flask-apl-hello-universe

        image: softwareshinobi/restful-flask-apl-hello-universe

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 8888:5000
