
services:
   
    python3-flask-apl-hello-world:

        container_name: python3-flask-apl-hello-world

        image: softwareshinobi/python3-flask-apl-hello-world

        build: 

            context: .

            dockerfile: Dockerfile

        ports:

            - 8888:5000
